- hosts: localhost
  connection: local
  tasks:

    - name: Create (or update) SQL Database
      azure.azcollection.azure_rm_sqlserver:
        resource_group: "{{ azure_resource_group }}"
        server_name: ansibletraining
        name: "{{ sql_database }}"
      register: create_db_output
    
    - name: Print Debug
      debug:
        var: create_db_output
