##
# Example: ansible-playbook -i inventory playbook.yml -k -K
##

---
- hosts: myinstance
  become: true
  user: studentxx
  tasks:
    - name: Print message
      debug:
        msg: "It is working"

    - name: Print setup properties
      setup:

    - name: Create user
      user:
        name: testplay01

    - name: Install package http
      package:
        name: httpd
        state: present

    - name: Enable and Up httpd
      service:
        name: httpd
        state: started
        enabled: yes
