##
# $ ansible-playbook aws-generate-inventory.yml
##

- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    environment: "{{ ENV | default('preproduction')}}"
    version: "{{ VER | default('latest') }}"
    inventory_dict: {}

  vars_files:
    - "./vars/aws-{{ environment }}-{{ version }}.yml"

  tasks:

    - name:  Extract EC2 instance information
      include_role:
        name: iac_aws_instance
      vars:
        action: add-public-ip-inventory
        instance: "{{ item.name }}"
        project: "{{ project_id }}"
        group: "ansiblenodes"
      loop: "{{ instances }}"

    - name: show all the hosts matching the pattern, i.e. all but the group www
      debug:
        var: aws_inventory

