##
# Example: ansible-playbook -i inventory handlers-playbook.yml -k -K
##

---
- hosts: myinstance
  become: true
  user: studentxx

  tasks:

    - block:

        - name: Install apache2 package
          package:
            name: apache2
            state: present
          notify: Restart httpd service

      rescue:

        - name: Install httpd package
          package:
            name: httpd
            state: present
          notify: Restart httpd service

      always:

        - name: Copy Apache config file
          copy:
            src: httpd.conf
            dest: /etc/httpd/httpd.conf
          notify: Restart httpd service

        - name: Install php package
          package:
            name: php
            state: present

        - name: Create php directory under /var/www/html
          file:
            path: /var/www/html/php
            state: directory

        - name: Copy php web page file
          copy:
            src: index.php
            dest: /var/www/html/php/index.php

  handlers:

    - name: Restart httpd service
      service:
        name: httpd
        state: restarted
        enabled: yes
